# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hutch Codes
email: jrhutch@live.com
description: > # this means to ignore newlines until "baseurl:"
  Jeremy Hutchinson's thoughts on software development 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hutchcodes.net" # the base hostname & protocol for your site
twitter_username: hutchcodes
github_username:  hutchcodes
avatar: /css/img/me.jpg

permalink: /:year/:month/:title/
disqus_site_id: finercode
excerpt_separator: <!--more-->
paginate: 5
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

sass:
  style: compressed

gems: [jekyll-paginate]

category_dir: "categories"
#category_layout: "index.html"


#GitHub defaults I cannot change  
lsi: false
#safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false

twitter: https://twitter.com/hutchcodes
linkedin: https://www.linkedin.com/in/jeremyhutchinson
feed: https://hutchcodes.net/feed/